// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ0EUxdNw_2FxiS5Lez_-hjoIXDLiAeic',
    appId: '1:152755390403:web:8472f378350d42e5291f76',
    messagingSenderId: '152755390403',
    projectId: 'e-commerce-app-a65f3',
    authDomain: 'e-commerce-app-a65f3.firebaseapp.com',
    storageBucket: 'e-commerce-app-a65f3.firebasestorage.app',
    measurementId: 'G-KPT1RD39GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuFQF_3v8ZO1Ch0w1lKHsqiPE3teBI2A',
    appId: '1:152755390403:android:898183aa6f086a52291f76',
    messagingSenderId: '152755390403',
    projectId: 'e-commerce-app-a65f3',
    storageBucket: 'e-commerce-app-a65f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Ze9ZDL7Sk4njMFy9gg7iy_sqN1iSZsA',
    appId: '1:152755390403:ios:d81a1cad89d0b801291f76',
    messagingSenderId: '152755390403',
    projectId: 'e-commerce-app-a65f3',
    storageBucket: 'e-commerce-app-a65f3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Ze9ZDL7Sk4njMFy9gg7iy_sqN1iSZsA',
    appId: '1:152755390403:ios:d81a1cad89d0b801291f76',
    messagingSenderId: '152755390403',
    projectId: 'e-commerce-app-a65f3',
    storageBucket: 'e-commerce-app-a65f3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ0EUxdNw_2FxiS5Lez_-hjoIXDLiAeic',
    appId: '1:152755390403:web:18e30739311afd31291f76',
    messagingSenderId: '152755390403',
    projectId: 'e-commerce-app-a65f3',
    authDomain: 'e-commerce-app-a65f3.firebaseapp.com',
    storageBucket: 'e-commerce-app-a65f3.firebasestorage.app',
    measurementId: 'G-TNWX9B35CZ',
  );
}
